CREATE TABLE `skills` (
	`ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`SkillName` VARCHAR(50) NOT NULL DEFAULT '0' COLLATE 'latin1_swedish_ci',
	`SkillPercent` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	`Order` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=7
;
