CREATE TABLE `projects` (
	`ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(50) NOT NULL DEFAULT '',
	`RepositoryLink` VARCHAR(5000) NULL DEFAULT '',
	`CompiledProjectLink` VARCHAR(5000) NULL DEFAULT '',
	`Description` TEXT NULL DEFAULT '',
	`ActiveDevelopment` BIT(1) NOT NULL DEFAULT b'0',
	`ImageURL` VARCHAR(5000) NULL DEFAULT '',
	PRIMARY KEY (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;
CREATE TABLE `jobs` (
	`ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`CompanyName` VARCHAR(150) NOT NULL,
	`StartDate` DATETIME NULL DEFAULT NULL,
	`EndDate` DATETIME NULL DEFAULT NULL,
	`Description` VARCHAR(1000) NULL DEFAULT NULL,
	`JobTitle` VARCHAR(50) NULL DEFAULT NULL,
	`Website` VARCHAR(100) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
)
ENGINE=InnoDB
;
